### PR TITLE
Fix integer inference on repeat operator

### LINKED ISSUE #804: Inline multi-dimensional array repeat not behaving properly when passed to a generic function
## Description

Compilation fails with `Failed to unroll or inline program. Check that main function arguments aren't used as array size or for-loop bounds`. Seems to be a compiler issue.

## Environment

- Compiler version: develop
- Operating system: Ubuntu 18.04 LTS

## Steps to Reproduce

```zokrates
def test<N>(field[N][N] t) -> field[N][N]:
    return t

def main() -> field[1][1]:
    return test([[0; 1]; 1]) // or just [[0]; 1], works with [[0]]
```

Note: Assigning the array to a variable and then passing it to the `test` function works, I have not found any issues with single dimension arrays.

### PR DESCRIPTION
**Pull request by Schaeff**
The type of the repeated element should be the inferred type, not the target type.

Closes #804

### CODE REVIEW

File: zokrates_core/src/typed_absy/integer.rs [hunk 1]
```diff
@@ -518,8 +518,10 @@ impl<'ast, T: Field> ArrayExpression<'ast, T> {
                     // try to convert the repeated element to the target type
```
Comment (dark64) [inline zokrates_core/src/typed_absy/integer.rs]: is this comment outdated now? should be the inferred type, not the target type I assume

Comment (Schaeff) [reply zokrates_core/src/typed_absy/integer.rs]: Good catch, the right word here is align, not convert: aligning `int[42]` to `field[N]` yields `field[42]`

**Review by dark64 — APPROVED** [review]
