### PR TITLE
Fix g16 onchain verification

### LINKED ISSUE #337: Gas Limit exceeded when verifying
> Gas estimation errored with the following message (see below). The
> transaction execution will likely fail. Do you want to force sending? 
> gas required exceeds allowance (6995524) or always failing transaction

Deployed contract successfully. Using remix on the Rinkeby network. Set gas limit to 7100000.

Program -

<pre>
// c0-c4 — candidates in the list, one of which not prime
// p, q — non-trivial factors for the non-prime candidate
def main(field c1, field c2) -> (field): 
  // TODO actual logic
    field c3=c1+c2
    return c3
</pre>

input - 

<pre>
{
        "proof": {
            "a": ["0x02150edc1a33c9b43af9f7f4065c1f678577661d87ec238079559d3dade4f74d", "0x1c8a3f37d1d2bb804c0bd7d3410f38ec194c7de66927167b78715789ae763c01"],
            "b": [["0x22bee54b128227589763635974e2c203cba3cd221498aa8861840ba3f16d5d7e", "0x0cef452d0a44024f96529c7a477f2116bc2b99cf5029153d1dd38b5d8a09d1e6"], ["0x28200db158548f83a066bde85aca312ba11202e38828f9dd11a45ccd91570934", "0x03705b0ac3fcecc21e75947abc8293aa70bba1226e8922faa9644b05c9367e55"]],
            "c": ["0x2ff6a6558296c58cd346eb5836afbe7546232c03a0353f0fd680a1309abf0374", "0x2b05227b0959dc0dcdddcc4686296efb0ec3aed61e4ec0706ee98dc5111099f6"]
        },
        "inputs": ["0x0000000000000000000000000000000000000000000000000000000000000001", "0x0000000000000000000000000000000000000000000000000000000000000003", "0x0000000000000000000000000000000000000000000000000000000000000004"]
    }
</pre>

### PR DESCRIPTION
**Pull request by Schaeff**
closes #337

### CODE REVIEW

File: zokrates_core/src/proof_system/bn128/utils/bellman.rs [hunk 1]
```diff
@@ -199,6 +201,95 @@ impl Circuit<Bn256> for Computation<FieldPrime> {
...
 }
 
+mod parse {
+    use lazy_static::lazy_static;
+
+    use super::*;
+    use regex::Regex;
+
+    lazy_static! {
+        static ref G2_REGEX: Regex = Regex::new(r"G2\(x=Fq2\(Fq\((?P<x0>0[xX][0-9a-fA-F]{64})\) \+ Fq\((?P<x1>0[xX][0-9a-fA-F]{64})\) \* u\), y=Fq2\(Fq\((?P<y0>0[xX][0-9a-fA-F]{64})\) \+ Fq\((?P<y1>0[xX][0-9a-fA-F]{64})\) \* u\)\)").unwrap();
```
Comment (stefandeml) [inline zokrates_core/src/proof_system/bn128/utils/bellman.rs]: Is the check for capital `X` necessary?
According to the implementation the string representation should always start with `0x` (https://github.com/zkcrypto/ff/blob/master/ff_derive/src/lib.rs#L148)

Comment (Schaeff) [reply zokrates_core/src/proof_system/bn128/utils/bellman.rs]: Good spot, I took a generic hex regex, don't think it's bad here
