### PR TITLE
Disallow the use of the private keyword on non-entrypoint functions

### LINKED ISSUE #1204: Parameter visibility on non-main functions
## Description

It is currently possible to use the visibility keyword on a parameter defined on a non-main function, which is semantically not valid.

## Environment

- Compiler version: 0.8.0
- Operating system: Ubuntu

## Steps to Reproduce

```zokrates
def mul(private field a) -> field { // `private` should not be allowed here
    return a * a;
}

def main(private field a, field b) {
    assert(mul(a) == b);
    return;
}
```

### PR DESCRIPTION
**Pull request by dark64**
Closes https://github.com/Zokrates/ZoKrates/issues/1204

### CODE REVIEW

File: zokrates_core/src/semantics.rs [hunk 1]
```diff
@@ -762,24 +763,40 @@ impl<'ast, T: Field> Checker<'ast, T> {
...
-                        );
+                        // parameters defined on a non-entrypoint function should not be set as private
+                        match (state.main_id != module_id || declaration.id != "main")
+                            && funct.arguments.iter().any(|a| a.private)
+                        {
+                            true => {
+                                errors.push(
+                                    ErrorInner {
+                                        pos: Some(pos),
+                                        message: "Private argument(s) are only allowed on the entrypoint function".into(),
```
Comment (Schaeff) [inline zokrates_core/src/semantics.rs]: This is not strict enough: in `from_ast.rs` we have the following:

```rust
let is_private = param
            .visibility
            .map(|v| match v {
                pest::Visibility::Private(_) => true,
                pest::Visibility::Public(_) => false,
            })
            .unwrap_or(false);
```

Based on this, the semantic checked cannot differentiate between `a` and `public a`, but the latter should not be allowed.

`absy` should be changed to include `Option<bool>` for the visibility, and it should be checked to be `None` for non main, and default to `true` for main.

Comment (Schaeff) [reply zokrates_core/src/semantics.rs]: Also the book seems to be lacking documentation on the visibility keywords, and generally on the entry point.

File: zokrates_core/src/semantics.rs [hunk 2]
```diff
@@ -3755,10 +3772,9 @@ mod tests {
     fn function1() -> FunctionNode<'static> {
         let statements = vec![Statement::Return(None).mock()];
 
-        let arguments = vec![untyped::Parameter {
-            id: untyped::Variable::immutable("a", UnresolvedType::FieldElement.mock()).mock(),
-            is_private: true,
-        }
+        let arguments = vec![untyped::Parameter::public(
```
Comment (Schaeff) [inline zokrates_core/src/semantics.rs]: Why is this change required?

File: zokrates_core/src/semantics.rs [hunk 3]
```diff
@@ -3952,18 +3970,18 @@ mod tests {
...
+            // def foo(field[3] a) {
             //   return;
             // }
             //
             // should succeed as P could be different from 3
 
             let mut f0 = function0();
 
-            f0.value.arguments = vec![untyped::Parameter::private(
+            f0.value.arguments = vec![untyped::Parameter::public(
```
Comment (Schaeff) [inline zokrates_core/src/semantics.rs]: Ok this seems to be related to what I mentioned above, the visibility should be an option on each parameter in the untyped ast, and in the typed ast it should probably only appear in TypedProgram, not on each function if possible.

**Review by Schaeff — CHANGES_REQUESTED** [review]
The changes to the semantic checker are nice but I think we should encode this more in our types in untyped and typed ast.

File: zokrates_core/src/semantics.rs (hunk 2 above)
Comment (dark64) [reply zokrates_core/src/semantics.rs]: I found this inconsistent with other tests, we use the wrapper functions everywhere except here. The parameter must be public otherwise the test fails because of the check introduced by this PR.

File: zokrates_stdlib/stdlib/signatures/verifyEddsa.zok [hunk 4]
```diff
@@ -29,7 +29,7 @@ import "utils/casts/u32_8_to_bool_256";
 ///
 /// Returns:
 ///     Return true for S being a valid EdDSA Signature, false otherwise.
-def main(private field[2] R, private field S, field[2] A, u32[8] M0, u32[8] M1, BabyJubJubParams context) -> bool {
+def main(field[2] R, field S, field[2] A, u32[8] M0, u32[8] M1, BabyJubJubParams context) -> bool {
```
Comment (dark64) [inline zokrates_stdlib/stdlib/signatures/verifyEddsa.zok:32]: @Schaeff also this is the one example I was talking about, this module had `private` parameters but is used as a submodule elsewhere

Comment (Schaeff) [reply zokrates_stdlib/stdlib/signatures/verifyEddsa.zok:32]: Right, this change makes sense!

**Comment by Schaeff** [comment]
Nice simplification of the implementation but I think we can go further by doing the following:

- Remove the `typed::GParameter` type entirely, replace all its occurrences with `typed::GVariable`
- Store a single array of `enum Visibility {Private, Public}` of visibilities at the `TypedProgram` level, as at that point I know they only exist for the entry point
- Change `fmt::Display` for `TypedProgram` so that when displaying the entry point, the array of visibilities is used

Thoughts?

**Comment by Schaeff** [comment]
Had a look at this suggestion and decided it should be a separate PR because a lot of tests have to be rewritten

File: changelogs/unreleased/1224-dark64 [hunk 5]
```diff
@@ -0,0 +1 @@
+Disallow the use of the `private` keyword on non-entrypoint functions
```
Comment (Schaeff) [inline changelogs/unreleased/1224-dark64]:
```suggestion
Disallow the use of the `private` and `public` keywords on non-entrypoint functions
```

File: zokrates_cli/examples/compile_errors/non_main_private_args.zok [hunk 6]
```diff
@@ -0,0 +1,8 @@
+def mul(private field a) -> field { // `private` should not be allowed here
```
Comment (Schaeff) [inline zokrates_cli/examples/compile_errors/non_main_private_args.zok:1]: we should also test for `public` here

**Review by Schaeff — APPROVED** [review]
LGTM!
