### PR TITLE
Release 0.4.11

### LINKED ISSUE #99: Unexpected result for < operator
I'm probably lacking some mathematical background here, but I was surprised to see that the following program

```
def main():
  return if 0 < 21888242871839275222246405745257275088548364400416034343698204186575808495616 then 1 else 0 fi
```

returns 0. I would have expected it to return 1, since 0 should be smaller than the large number. 

Does this have something to do with interpreting the larger number as a signed integer (-1)? If so, where would be the "underflow point" for which i < i-1?

I'm trying to write a proof that is dealing with potentially very large unsigned integers and would like to know what the highest number `n` is, for which `0 < n`.

### PR DESCRIPTION
**Pull request by Schaeff**
This is a patch release to fix a vulnerability with the `a < b` operator when `| a - b |` is large.
- fixes #99 
- fixes deprecated `try!` macro

### CODE REVIEW

File: zokrates_core/src/flatten/mod.rs [hunk 1]
```diff
@@ -147,23 +147,23 @@ impl<'ast> Flattener<'ast> {
                 // lhs
```
Comment (JacobEberhardt) [inline zokrates_core/src/flatten/mod.rs]: The comment 
`check that lhs and rhs are within the right range, ie, their last two bits are zero`
could be made clear by replacing with:
`check that lhs and rhs are within the right range, i.e., their highest two highest value bits are 0. We use big-endian here, so these bits are laid out at postitions 0 and 1 by the bits directive`
