### PR TITLE
Fix zokrates_js build script, filter .zok files

### LINKED ISSUE #1212: Ignore .DS_Store files in zjs build script

### PR DESCRIPTION
**Pull request by dark64**
closes https://github.com/Zokrates/ZoKrates/issues/1212

### CODE REVIEW

File: zokrates_js/build.rs [hunk 1]
```diff
@@ -14,7 +14,13 @@ fn export_stdlib() {
     for entry in WalkDir::new(root)
         .into_iter()
         .map(Result::unwrap)
-        .filter(|e| !e.file_type().is_dir())
+        .filter(|e| {
+            !e.file_type().is_dir()
+                && e.file_name()
```
Comment (Schaeff) [inline zokrates_js/build.rs]: https://doc.rust-lang.org/std/path/struct.Path.html#method.extension should be used instead

**Review by Schaeff — APPROVED** [review]
