### PR TITLE
Fix parser multidef confusion

### LINKED ISSUE #588: Parser misinterprets definition as multidef
```
field a = f() + 1
```

Since we want to catch all statements of the form `identifiers = function_call`, we try this rule first before a simple definition `assignee = expression`.

Sadly in this case it matches `field a = f()` and a parsing error is returned.

### PR DESCRIPTION
**Pull request by Schaeff**
fixes #588

### CODE REVIEW

File: zokrates_core/src/absy/from_ast.rs [hunk 1]
```diff
@@ -966,4 +966,147 @@ mod tests {
...
+    #[test]
+    fn declarations() {
+        use self::pest::Span;
+
+        let span = Span::new(&"", 0, 0).unwrap();
+
+        // For different definitions, we generate declarations
+        // Case 1: `id = expr` where `expr` is not a function call
+        // This is a simple assignment, doesn't implicitely declare a variable
+        // A `Definition` is generatedm and no `Declaration`s
```
Comment (JacobEberhardt) [inline zokrates_core/src/absy/from_ast.rs:978]:
```suggestion
        // A `Definition` is generated and no `Declaration`s
```

File: zokrates_core/src/absy/from_ast.rs [hunk 2]
```diff
@@ -966,4 +966,147 @@ mod tests {
...
+
+        assert_eq!(statements.len(), 1);
+        match &statements[0].value {
+            absy::Statement::MultipleDefinition(..) => {}
+            s => {
+                panic!("should be a Definition, found {}", s);
+            }
+        };
+        // Case 3: `ids = expr` where `expr` is a function call
+        // This implicitely declares all variables which are type annotated
```
Comment (JacobEberhardt) [inline zokrates_core/src/absy/from_ast.rs:1054]: I would argue that the `type identifier`statement on the left side is an explicit declaration.
