### PR TITLE
Handle errors more gracefully in propagation step where applicable

### LINKED ISSUE #811: Propagation panics on user errors
## Description

A bunch of user errors lead to panic (out of bounds, etc) while other panics in propagation are justified (internal errors). Sort these and fails gracefully when applicable.

## Environment

- Compiler version: develop

## Steps to Reproduce

```
def main():
   u32 N = 3
   field[1] a = [1]
   field b = a[N]
   return
```

### PR DESCRIPTION
**Pull request by dark64**
https://github.com/Zokrates/ZoKrates/issues/811

### CODE REVIEW

File: zokrates_core/src/static_analysis/propagation.rs [hunk 1]
```diff
@@ -912,147 +940,150 @@ impl<'ast, 'a, T: Field> ResultFolder<'ast, T> for Propagator<'ast, 'a, T> {
...
-                    (e1, UExpressionInner::Value(n2)) => FieldElementExpression::Pow(
+                    (e1, UExpressionInner::Value(n2)) => Ok(FieldElementExpression::Pow(
                         box e1,
                         box UExpressionInner::Value(n2).annotate(UBitwidth::B32),
-                    ),
-                    (_, e2) => unreachable!(format!(
-                        "non-constant exponent {} detected during static analysis",
-                        e2.annotate(UBitwidth::B32)
                     )),
+                    (_, e2) => Err(Error::NonConstantExponent(format!(
```
Comment (Schaeff) [inline zokrates_core/src/static_analysis/propagation.rs]: I'm surprised clippy doesnt suggest using `to_string` instead of `format!`

File: zokrates_core/src/static_analysis/propagation.rs [hunk 2]
```diff
@@ -1135,29 +1163,32 @@ impl<'ast, 'a, T: Field> ResultFolder<'ast, T> for Propagator<'ast, 'a, T> {
                             .unwrap()
                             .1
                         {
-                            TypedExpression::FieldElement(s) => s,
+                            TypedExpression::FieldElement(s) => Ok(s),
                             _ => unreachable!("????"),
```
Comment (Schaeff) [inline zokrates_core/src/static_analysis/propagation.rs]: This message could be better, if it's in the scope of this PR to also make the panics clearer.

File: zokrates_core/src/static_analysis/propagation.rs (hunk 1 above)
Comment (dark64) [reply zokrates_core/src/static_analysis/propagation.rs]: that is surprising :|, will refactor this to use `to_string`

**Review by Schaeff — APPROVED** [review]
👍
